# choose trusty for c++11
dist: trusty

language: cpp

compiler: gcc

script:
  # compile code and build unit tests
  - make
  
  # run catch unit tests
  - find . -name utests -print | while read f; do ./"$f"; done
